### ISSUE TITLE
Strip HTML Whitespace characters

### ISSUE THREAD

**Issue by Chocrates** [jasonmacgowan/actions-parse-issue#5]
In some templates that create issues they will create issue bodies like the following:

```<p>Name: Name Of Person</p>```  

This causes the key to be `<p>Name` and the value to be `Name Of Person</p>`  
We should strip these or given an option to the user to strip them if desired

**Comment by jasonmacgowan** [comment]
#6 will address most use cases that don't fit well into `key: value`

Still, I think it's worth updating the default regex to match `\w` instead of `.`

**Comment by Chocrates** [comment]
Ah agreed, looks like that PR will fix our use case.
